stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx-hello/Dockerfile
      buildContext: ./nginx-hello
      tag: nginxdemos-hello-github
      pushRemote: true
      registry: 127.0.0.1:34016
- name: Run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
