stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx-hello/Dockerfile
      buildContext: ./nginx-hello
      tag: nginxdemos-hello:1.0
      pushRemote: true
      registry: 127.0.0.1:34108
- name: Run
  steps:
  - applyYamlConfig:
      path: ./nginx-hello/deployment.yaml
timeout: 60
notification: {}
