stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx-demos/nginx-hello/Dockerfile
      buildContext: .
      tag: nginxdemos-hello-github
      pushRemote: true
      registry: 127.0.0.1:34656
timeout: 60
notification: {}
