stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./nginx-hello/Dockerfile
      buildContext: ./nginx-hello
      tag: nginxdemos-hello-github
      pushRemote: true
      registry: 127.0.0.1:34656
timeout: 60
notification: {}
