stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./kubernetes-demo/third/nginxplus/Dockerfile
      buildContext: .
      tag: nginxdemos-hello
      registry: 127.0.0.1:34356
timeout: 60
notification: {}
