stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginxdemos-hello-github
      registry: 127.0.0.1:34656
timeout: 60
notification: {}
