stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: /NGINX-Demos/nginx-hello/Dockerfile
      buildContext: /NGINX-Demos/nginx-hello
      tag: nginxdemos-hello-github
      registry: 127.0.0.1:34108
- name: Run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
