kind: Service
apiVersion: v1
metadata:
  name: nginxdemos-hello
spec:
  selector:
    app: nginxdemos-hello
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemos-hello
  labels:
    app: nginxdemos-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdemos-hello
  template:
    metadata:
      labels:
        app: nginxdemos-hello
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginxdemos-hello
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
